language: generic
services: docker

env:
  - BASE=alpine VERSION=12
  - BASE=alpine VERSION=13
  - BASE=alpine VERSION=14
  - BASE=alpine VERSION=latest
  - BASE=ruby VERSION=12
  - BASE=ruby VERSION=13
  - BASE=ruby VERSION=14
  - BASE=ruby VERSION=latest

jobs:
  include:
    - stage: Build
      script: ./ci.sh build
    - stage: Push
      script: ./ci.sh push

stages:
  - Build
  - name: Push
    if: branch = master AND repo = johnbarney/docker-knife
